version: '1'
services:

  db:
    image: mysql:8.3.0
    healthcheck:
      test: "exit 0"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scootin_aboot

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/go/src/api
    ports:
      - "8080:8080"
    environment:
      PUBLIC_HOST: 0.0.0.0
      DB_HOST: docker.for.mac.localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: scootin_aboot
    links:
      - db
    depends_on:
      - db

volumes:
  db_data: